apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  # Todo: 
  # * Configure storage: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L734 and https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
  valuesContent: |
    grafana:
      adminPassword: ${grafana_password}